version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev:
        patterns: ["@types/*", "prettier", "tsx", "typescript", "typedoc"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
