/**
 * Generate a valid Noir `Prover.toml` for `corridor-circuits`.
 *   npx tsx scripts/gen-fixture.ts > ../corridor-circuits/corridor_eligibility/Prover.toml
 */
import { makeFixture, toProverToml } from "../src/fixture.js";
import { buildWitness } from "../src/witness.js";
import { toBytes32 } from "../src/hex.js";
import type { CorridorPolicy } from "../src/types.js";

const CID = "0x0000000000000000000000000000000000000000000000000000000000000004" as const;
const NOW = 1_000_000;

const holder = { holderSecret: 12345n, tier: 3, expiry: 9_000_000, issuerId: 7n, salt: 42n };
const fx = makeFixture({ holder, index: 3n, revoked: [], minTier: 2 });

const policy: CorridorPolicy = {
  operator: "G".padEnd(56, "A"),
  acceptedIssuers: [toBytes32(7n)],
  minTier: fx.policy.minTier,
  requiredDisclosures: 0,
  credentialRoot: fx.policy.credentialRoot,
  revocationRoot: fx.policy.revocationRoot,
  rootEpoch: 1n,
  verifier: "C".padEnd(56, "A"),
  vkHash: toBytes32(9n),
  nowToleranceSecs: 300n,
  paused: false,
};

const w = buildWitness(
  fx.credential,
  policy,
  { disclosedTag: 2, auditorPubkey: toBytes32(0n), auditorNonce: toBytes32(7n) },
  { corridorId: CID, now: NOW },
);

process.stdout.write(
  "# Generated by corridor-sdk/scripts/gen-fixture.ts — a VALID witness.\n" +
    "# Regenerate after any change to the circuit's public-input layout.\n\n" +
    toProverToml(w.publicInputs, w.privateInputs),
);
