/**
 * Testnet E2E variant of gen-circuit-fixture.ts: same deterministic issuer
 * key, holder secret, tier/epoch/salt/auditor constants as the committed
 * fixture — but with `now` at generation time and `expiry` 90 days out, so
 * the proof passes `enter`'s ledger-time skew check.
 *
 *   npx tsx scripts/gen-testnet-fixture.ts > /tmp/e2e-prove/Prover.toml
 */
import { publicKey, sign, GRUMPKIN_P } from "../src/schnorr.js";
import { poseidon2 } from "../src/poseidon.js";
import { toBytes32, bytes32ToBigInt, BN254_FR } from "../src/hex.js";

const CID = 4n;
const NOW = BigInt(Math.floor(Date.now() / 1000));
const EXPIRY = NOW + 90n * 24n * 60n * 60n;

// deterministic issuer key — identical to the committed fixture
const sk = toBytes32(
  0x1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809n % GRUMPKIN_P,
);
const pk = publicKey(sk);

const holderSecret =
  0x0affee0decaf0badf00d1234567890abcdef0affee0decaf0badf00d12345678n % BN254_FR;
const tier = 4n;
const credEpoch = 7n;
const salt = 42n;
const auditorPubkey = 0n;
const auditorNonce = 77n;

const holderBinding = poseidon2([holderSecret, salt]);
const message = toBytes32(poseidon2([holderBinding, tier, EXPIRY, credEpoch]));
const sig = sign(sk, message);

const issuerId = poseidon2([bytes32ToBigInt(pk.x), bytes32ToBigInt(pk.y)]);
const nullifier = poseidon2([holderSecret, CID]);
const auditorBlob = poseidon2([auditorPubkey, tier, issuerId, nullifier, auditorNonce]);

const f = (v: bigint | string) =>
  `0x${(typeof v === "bigint" ? v : bytes32ToBigInt(v as `0x${string}`)).toString(16)}`;

const proverToml = `# GENERATED by corridor-sdk/scripts/gen-testnet-fixture.ts — a VALID witness
# with fresh timestamps for the testnet enter() E2E.
corridor_id = "${f(CID)}"
min_tier = "3"
now = "${NOW}"
nullifier = "${f(nullifier)}"
disclosed_tag = "2"
issuer_id = "${f(issuerId)}"
min_cred_epoch = "1"
auditor_pubkey = "${f(auditorPubkey)}"
auditor_blob = "${f(auditorBlob)}"
holder_secret = "${f(holderSecret)}"
tier = "${tier}"
expiry = "${EXPIRY}"
cred_epoch = "${credEpoch}"
salt = "${f(salt)}"
issuer_pk_x = "${f(pk.x)}"
issuer_pk_y = "${f(pk.y)}"
sig_s_lo = "${f(sig.sLo)}"
sig_s_hi = "${f(sig.sHi)}"
sig_e_lo = "${f(sig.eLo)}"
sig_e_hi = "${f(sig.eHi)}"
auditor_nonce = "${f(auditorNonce)}"
`;

process.stdout.write(proverToml);
process.stderr.write(`now=${NOW} expiry=${EXPIRY} issuer_id=${f(issuerId)}\n`);
