/**
 * Emit the circuit's `fixture.nr` (a valid signed witness for `nargo test`)
 * and a `Prover.toml`. Run from corridor-sdk:
 *   npx tsx scripts/gen-circuit-fixture.ts
 */
import { publicKey, sign, GRUMPKIN_P } from "../src/schnorr.js";
import { poseidon2 } from "../src/poseidon.js";
import { toBytes32, bytes32ToBigInt, BN254_FR } from "../src/hex.js";

const CID = 4n;
const NOW = 1_000_000n;

// deterministic issuer key for a stable fixture
const sk = toBytes32(
  0x1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809n % GRUMPKIN_P,
);
const pk = publicKey(sk);

const holderSecret =
  0x0affee0decaf0badf00d1234567890abcdef0affee0decaf0badf00d12345678n % BN254_FR;
const tier = 4n;
const expiry = 9_000_000n;
const credEpoch = 7n;
const salt = 42n;
const auditorPubkey = 0n;
const auditorNonce = 77n;

const holderBinding = poseidon2([holderSecret, salt]);
const message = toBytes32(poseidon2([holderBinding, tier, expiry, credEpoch]));
const sig = sign(sk, message);

const issuerId = poseidon2([bytes32ToBigInt(pk.x), bytes32ToBigInt(pk.y)]);
const nullifier = poseidon2([holderSecret, CID]);
const auditorBlob = poseidon2([auditorPubkey, tier, issuerId, nullifier, auditorNonce]);

const f = (v: bigint | string) =>
  `0x${(typeof v === "bigint" ? v : bytes32ToBigInt(v as `0x${string}`)).toString(16)}`;

const fixtureNr = `//! GENERATED by corridor-sdk/scripts/gen-circuit-fixture.ts — a valid signed
//! witness. Regenerate after any change to the statement layout or the
//! Schnorr scheme.

use crate::eligibility::{Public, Witness};

pub fn good() -> (Public, Witness) {
    let p = Public {
        corridor_id: ${f(CID)},
        min_tier: 3,
        now: ${NOW},
        nullifier: ${f(nullifier)},
        disclosed_tag: 2,
        issuer_id: ${f(issuerId)},
        min_cred_epoch: 1,
        auditor_pubkey: ${f(auditorPubkey)},
        auditor_blob: ${f(auditorBlob)},
    };
    let w = Witness {
        holder_secret: ${f(holderSecret)},
        tier: ${tier},
        expiry: ${expiry},
        cred_epoch: ${credEpoch},
        salt: ${f(salt)},
        issuer_pk_x: ${f(pk.x)},
        issuer_pk_y: ${f(pk.y)},
        sig_s_lo: ${f(sig.sLo)},
        sig_s_hi: ${f(sig.sHi)},
        sig_e_lo: ${f(sig.eLo)},
        sig_e_hi: ${f(sig.eHi)},
        auditor_nonce: ${f(auditorNonce)},
    };
    (p, w)
}
`;

const proverToml = `# GENERATED by corridor-sdk/scripts/gen-circuit-fixture.ts — a VALID witness.
corridor_id = "${f(CID)}"
min_tier = "3"
now = "${NOW}"
nullifier = "${f(nullifier)}"
disclosed_tag = "2"
issuer_id = "${f(issuerId)}"
min_cred_epoch = "1"
auditor_pubkey = "${f(auditorPubkey)}"
auditor_blob = "${f(auditorBlob)}"
holder_secret = "${f(holderSecret)}"
tier = "${tier}"
expiry = "${expiry}"
cred_epoch = "${credEpoch}"
salt = "${f(salt)}"
issuer_pk_x = "${f(pk.x)}"
issuer_pk_y = "${f(pk.y)}"
sig_s_lo = "${f(sig.sLo)}"
sig_s_hi = "${f(sig.sHi)}"
sig_e_lo = "${f(sig.eLo)}"
sig_e_hi = "${f(sig.eHi)}"
auditor_nonce = "${f(auditorNonce)}"
`;

// By default this is a smoke test: it builds a real signed witness and prints
// it, so SDK CI can run it in an isolated checkout (no corridor-circuits
// sibling). Pass `--write` to overwrite the circuit's fixture.nr + Prover.toml.
import { writeFileSync, existsSync } from "node:fs";

if (process.argv.includes("--write")) {
  const circ = new URL(
    "../../corridor-circuits/corridor_eligibility/",
    import.meta.url,
  );
  if (!existsSync(circ)) {
    console.error(
      `--write: ${circ.pathname} not found — clone corridor-circuits as a sibling`,
    );
    process.exit(1);
  }
  writeFileSync(new URL("src/eligibility/fixture.nr", circ), fixtureNr);
  writeFileSync(new URL("Prover.toml", circ), proverToml);
  console.error("wrote fixture.nr + Prover.toml to corridor-circuits");
} else {
  process.stdout.write(
    `// --- fixture.nr ---\n${fixtureNr}\n// --- Prover.toml ---\n${proverToml}`,
  );
}
